# -*- coding: utf-8 -*-
"""kerasSentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1suP1fniC0k-JmHCCEAwJMv7bHTAxgssd
"""

import numpy as np
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Flatten, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load IMDB Dataset
vocab_size = 10000

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

# Padding
max_len = 200

X_train = pad_sequences(X_train, maxlen=max_len)
X_test = pad_sequences(X_test, maxlen=max_len)

X_train.shape

model = Sequential()

# Embedding Layer
model.add(Embedding(
    input_dim=vocab_size,
    output_dim=32,
    input_length=max_len
))

# RNN Layer
model.add(SimpleRNN(
    units=32,
    return_sequences=True
))

# Flatten Layer
model.add(Flatten())

# Output Layer
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# Train
history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_split=0.2
)

# Evaluate
loss, acc = model.evaluate(X_test, y_test)

print("Test Accuracy:", acc)
